version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule: weekly

  - package-ecosystem: npm
    directory: "/"
    schedule: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule: weekly