title: "Blake Oxford Portfolio"
description: "Portfolio of Blake Oxford – IT Director, Business Systems Manager, Digital Transformation Consultant, Enterprise Solutions Architect, and Operations & Strategy Manager."
theme: jekyll-theme-cayman
permalink: /:title/

# Enable Jekyll plugins on GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# (Optional) Google Analytics – replace UA-XXXXXX-X with your tracking ID
google_analytics: UA-XXXXXX-X

# Define a collection for projects
collections:
  projects:
    output: true
