title: "Blake Oxford Portfolio"
description: "Portfolio of Blake Oxford – IT Director, Business Systems Manager, Digital Transformation Consultant, Enterprise Solutions Architect, and Operations & Strategy Manager."
permalink: pretty

# Enable Jekyll plugins on GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination Settings
paginate: 6
paginate_path: "/projects/page:num/"

# Define a collection for projects
collections:
  projects:
    output: true

# Metadata
author: "Blake Oxford"
email: "blakepoxford@outlook.com"

# Sitemap Configuration
sitemap:
  exclude:
    - /404.html

# Base URL for subdirectory hosting
baseurl: "" # Replace with your subdirectory name or leave empty for root