title: "Blake Oxford Portfolio"
description: "Portfolio of Blake Oxford – IT Director, Business Systems Manager, Digital Transformation Consultant, Enterprise Solutions Architect, and Operations & Strategy Manager."
permalink: pretty

# Ensure compatibility with GitHub Pages
url: https://blakeox.github.io
baseurl: "" # Adjusted for root hosting

# Enable Jekyll plugins on GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

# Define a collection for projects
collections:
  projects:
    output: true

# Metadata
author: "Blake Oxford"
email: "blakepoxford@outlook.com"

# Sitemap Configuration
sitemap:
  exclude:
    - /404.html

# Exclude unnecessary files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - lighthouserc.json
  - axe-test.js
  - .github/

# Enable plugins supported by GitHub Pages
github:
  is_project_page: true

# Other settings
markdown: kramdown
kramdown:
  input: GFM


sass:
  sass_dir: _sass
  style: compressed # Optional: Use 'compressed' for minified CSS

pagination:
  enabled: true
  per_page: 5
  permalink: /page/:num/
  title: ":title - Page :num"
  sort_field: "date"
  sort_reverse: true