title: "Blake Oxford Portfolio"
description: >
  Portfolio of Blake Oxford
  — IT Director, Business Systems Manager,
  Digital Transformation Consultant,
  Enterprise Solutions Architect, and
  Operations & Strategy Manager.
permalink: pretty

# Site URL & base (for root‑hosted GitHub Pages)
url: "https://blakeox.github.io"
baseurl: ""

# Author metadata
author: "Blake Oxford"
email: "blakepoxford@outlook.com"

# Collections
collections:
  projects:
    output: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Pagination
pagination:
  enabled: true
  per_page: 5
  permalink: /page/:num/
  title: ":title - Page :num"
  sort_field: "date"
  sort_reverse: true

# SEO & social
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed            # ➤ adds an RSS feed at /feed.xml
  - jekyll-minifier        # ➤ minifies HTML/CSS/JS output

twitter:
  card: summary_large_image
  site: "@blakeox"
  creator: "@blakeox"

og:
  title: "Blake Oxford Portfolio"
  description: "Portfolio of Blake Oxford — IT Director, Business Systems Manager, Digital Transformation Consultant, Enterprise Solutions Architect, and Operations & Strategy Manager."
  type: "website"
  url: "https://blakeox.github.io"
  image: "/assets/images/og-image.jpg"

# Sitemap config
sitemap:
  exclude:
    - /404.html

# Exclude any files & folders you don’t want Jekyll to parse
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - lighthouserc.json
  - axe-test.js
  - .github/
  - _site
  - jekyll.log
  - node_modules
  - vendor              # ◂──<- added: skip all bundled gems

# GitHub Pages settings
github:
  is_project_page: true
  token: ENV['JEKYLL_GITHUB_TOKEN']