title: "Blake Oxford Portfolio"
description: "Portfolio of Blake Oxford – IT Director, Business Systems Manager, Digital Transformation Consultant, Enterprise Solutions Architect, and Operations & Strategy Manager."
theme: jekyll-theme-cayman
permalink: /:title/
