name: CI & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js (with Yarn cache)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: yarn

      - run: yarn install --frozen-lockfile
      - run: npm run lint:js
      - run: npm run lint:scss

  test:
    name: Build & Test Site
    needs: lint
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js (with Yarn cache)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: yarn

      - name: Set up Ruby (with Bundler cache)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Verify JEKYLL_GITHUB_TOKEN
        run: test -n "$JEKYLL_GITHUB_TOKEN"
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Validate HTML & links
        run: |
          gem install html-proofer
          htmlproofer ./_site \
            --assume-extension \
            --disable-external \
            --allow-missing-href \                       # ignore <a> without href  [oai_citation_attribution:0‡GitHub](https://github.com/gjtorikian/html-proofer/blob/main/README.md)
            --ignore-empty-mailto \                       # allow mailto: without address  [oai_citation_attribution:1‡GitHub](https://github.com/gjtorikian/html-proofer/blob/main/README.md)
            --checks 'Links,Scripts,Favicon,OpenGraph'   # skip the 'Images' checks entirely  [oai_citation_attribution:2‡GitHub](https://github.com/gjtorikian/html-proofer/blob/main/README.md)

      - name: Serve static `_site`
        run: |
          npm install -g http-server
          http-server ./_site -p 4000 &
          sleep 5

      - name: Run Lighthouse CI
        run: lhci autorun \
          --chrome-flags="--ignore-certificate-errors --disable-web-security" \
          --url=http://localhost:4000

      - name: Run Axe accessibility tests
        run: node axe-test.js --url=http://localhost:4000

      - name: Upload Axe results
        uses: actions/upload-artifact@v4
        with:
          name: axe-results
          path: axe-results