name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install Bundler and Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Install dependencies
      run: |
        npm install -g @lhci/cli puppeteer @axe-core/puppeteer

    - name: Install Node.js Fetch Polyfill
      run: |
        npm install node-fetch@2

    - name: Polyfill Fetch for Node.js
      run: |
        echo "require('node-fetch');" >> axe-test.js

    - name: Increase Jekyll Server Timeout
      run: |
        echo "timeout: 30000" >> lighthouserc.json

    - name: Run Lighthouse CI
      run: |
        lhci autorun

    - name: Run Axe Accessibility Tests
      run: |
        node axe-test.js