name: CI & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (with Yarn cache)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: yarn

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Lint JavaScript
        run: npm run lint:js

      - name: Lint SCSS
        run: npm run lint:scss

  test:
    name: Build & Test Site
    needs: lint
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (with Yarn cache)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: yarn

      - name: Set up Ruby (with Bundler cache)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Verify JEKYLL_GITHUB_TOKEN
        run: test -n "$JEKYLL_GITHUB_TOKEN"
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Validate HTML & links
        run: |
          gem install html-proofer
          htmlproofer ./_site \
            --assume-extension \
            --check-html \
            --disable-external

      - name: Serve static `_site`
        run: |
          npm install -g http-server
          http-server ./_site -p 4000 &
          sleep 5

      - name: Run Lighthouse CI
        run: lhci autorun \
          --chrome-flags="--ignore-certificate-errors --disable-web-security" \
          --url=http://localhost:4000

      - name: Run Axe accessibility tests
        run: node axe-test.js --url=http://localhost:4000

      - name: Upload Axe results
        uses: actions/upload-artifact@v4
        with:
          name: axe-results
          path: axe-results