name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (with Yarn cache)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Set up Ruby (with Bundler cache)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Verify JEKYLL_GITHUB_TOKEN
        run: |
          if [ -z "${JEKYLL_GITHUB_TOKEN}" ]; then
            echo "ERROR: Missing JEKYLL_GITHUB_TOKEN" && exit 1
          fi
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Start Jekyll Server
        run: |
          nohup bundle exec jekyll serve --host 0.0.0.0 --port 4000 > jekyll.log 2>&1 &
          for i in {1..30}; do
            curl --silent --fail http://localhost:4000 && break
            sleep 2
          done

      - name: Test Jekyll Server
        run: curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:4000

      - name: Run Lighthouse CI
        run: lhci autorun --chrome-flags="--ignore-certificate-errors --disable-web-security"

      - name: Run Axe accessibility tests
        run: node axe-test.js

      - name: Upload Axe results
        uses: actions/upload-artifact@v4
        with:
          name: axe-results
          path: axe-results