name: Build & Deploy Jekyll

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'

      - run: |
          gem install bundler
          bundle install
          bundle exec jekyll build