name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Build Jekyll site
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - run: |
          bundle exec jekyll clean
          bundle exec jekyll build

      - id: deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - uses: actions/deploy-pages@v4